from easydict import EasyDict as edict
import yaml

"""
Add default config for MPLTTrack.
"""
cfg = edict()

# MODEL
cfg.MODEL = edict()
cfg.MODEL.PRETRAIN_FILE = "mae_pretrain_vit_base.pth"
cfg.MODEL.EXTRA_MERGER = False

cfg.MODEL.RETURN_INTER = False
cfg.MODEL.RETURN_STAGES = [2, 5, 8, 11]

# MODEL.LANGUAGE
cfg.MODEL.LANGUAGE = edict()
cfg.MODEL.LANGUAGE.USE = False
cfg.MODEL.LANGUAGE.MODEL_NAME_OR_PATH = "roberta-base"
cfg.MODEL.LANGUAGE.MAX_LENGTH = 48
cfg.MODEL.LANGUAGE.DROPOUT = 0.1
cfg.MODEL.LANGUAGE.FREEZE = True
cfg.MODEL.LANGUAGE.LOCAL_FILES_ONLY = True
cfg.MODEL.LANGUAGE.RANDOM_INIT_IF_MISSING = False
cfg.MODEL.LANGUAGE.ROUTER_TEMPERATURE = 1.0
cfg.MODEL.LANGUAGE.MATCHING_STRENGTH = 0.03
cfg.MODEL.LANGUAGE.EXPERT_RESIDUAL_WEIGHT = 0.12
cfg.MODEL.LANGUAGE.TOKEN_KEEP_RATIO = 0.80
cfg.MODEL.LANGUAGE.TOKEN_MASK_STRENGTH = 0.03
cfg.MODEL.LANGUAGE.ROUTE_LANGUAGE_MAX = 0.25
cfg.MODEL.LANGUAGE.MATCH_LOGIT_SCALE_MAX = 20.0
cfg.MODEL.LANGUAGE.MATCH_LOGIT_SCALE_TRAINABLE = True
cfg.MODEL.LANGUAGE.RELIABILITY_RESIDUAL_GATE = True
cfg.MODEL.LANGUAGE.TRAIN_WARMUP_ITERS = 0
cfg.MODEL.LANGUAGE.TRAIN_RAMP_ITERS = 0
cfg.MODEL.LANGUAGE.USE_DEPTH_IMAGE_RELIABILITY = False
cfg.MODEL.LANGUAGE.DEPTH_IMAGE_RELIABILITY_WEIGHT = 0.5

# MODEL.BACKBONE
cfg.MODEL.BACKBONE = edict()
cfg.MODEL.BACKBONE.TYPE = "vit_base_patch16_224"
cfg.MODEL.BACKBONE.STRIDE = 16
cfg.MODEL.BACKBONE.MID_PE = False
cfg.MODEL.BACKBONE.SEP_SEG = False
cfg.MODEL.BACKBONE.CAT_MODE = 'direct'
cfg.MODEL.BACKBONE.MERGE_LAYER = 0
cfg.MODEL.BACKBONE.ADD_CLS_TOKEN = False
cfg.MODEL.BACKBONE.CLS_TOKEN_USE_MODE = 'ignore'

cfg.MODEL.BACKBONE.CE_LOC = []
cfg.MODEL.BACKBONE.CE_KEEP_RATIO = []
cfg.MODEL.BACKBONE.CE_TEMPLATE_RANGE = 'ALL'  # choose between ALL, CTR_POINT, CTR_REC, GT_BOX

# RGBT.BACKBONE
cfg.MODEL.BACKBONE.MPLT_LOC = []
cfg.MODEL.BACKBONE.RGB_ONLY = False
cfg.MODEL.BACKBONE.RGBT_UNSHARE = False

# MODEL.HEAD
cfg.MODEL.HEAD = edict()
cfg.MODEL.HEAD.TYPE = "CENTER"
cfg.MODEL.HEAD.NUM_CHANNELS = 256

# TRAIN
cfg.TRAIN = edict()
cfg.TRAIN.LR = 0.0001
cfg.TRAIN.WEIGHT_DECAY = 0.0001
cfg.TRAIN.EPOCH = 500
cfg.TRAIN.LR_DROP_EPOCH = 400
cfg.TRAIN.BATCH_SIZE = 16
cfg.TRAIN.NUM_WORKER = 8
cfg.TRAIN.OPTIMIZER = "ADAMW"
cfg.TRAIN.BACKBONE_MULTIPLIER = 0.1
cfg.TRAIN.GIOU_WEIGHT = 2.0
cfg.TRAIN.L1_WEIGHT = 5.0
cfg.TRAIN.LANGUAGE_TARGET_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_CONTEXT_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_ROUTE_WEIGHT = 0.002
cfg.TRAIN.LANGUAGE_ROUTE_SUPERVISION_WEIGHT = 0.0
cfg.TRAIN.LANGUAGE_ROUTE_ENTROPY_WEIGHT = 1.0
cfg.TRAIN.LANGUAGE_ROUTE_RGB_LOW_RELIABILITY = 0.50
cfg.TRAIN.LANGUAGE_ROUTE_RGB_HIGH_RELIABILITY = 0.28
cfg.TRAIN.LANGUAGE_ROUTE_DEPTH_LOW_RELIABILITY = 0.15
cfg.TRAIN.LANGUAGE_ROUTE_DEPTH_HIGH_RELIABILITY = 0.42
cfg.TRAIN.LANGUAGE_ROUTE_LANG_LOW_RELIABILITY = 0.005
cfg.TRAIN.LANGUAGE_ROUTE_LANG_HIGH_RELIABILITY = 0.03
cfg.TRAIN.LANGUAGE_MATCH_SCALE_WEIGHT = 0.05
cfg.TRAIN.LANGUAGE_MATCH_SCALE_TARGET = 10.0
cfg.TRAIN.SAVE_EVERY_EPOCH = False
cfg.TRAIN.SAVE_INTERVAL_STEPS = 0
cfg.TRAIN.FREEZE_BN_STATS = False
cfg.TRAIN.FREEZE_LAYERS = [0, ]
cfg.TRAIN.TRAINABLE_PARAM_KEYWORDS = []
cfg.TRAIN.PRINT_INTERVAL = 50
cfg.TRAIN.VAL_EPOCH_INTERVAL = 20
cfg.TRAIN.GRAD_CLIP_NORM = 0.1
cfg.TRAIN.AMP = False

cfg.TRAIN.CE_START_EPOCH = 20  # candidate elimination start epoch
cfg.TRAIN.CE_WARM_EPOCH = 80  # candidate elimination warm up epoch
cfg.TRAIN.DROP_PATH_RATE = 0.1  # drop path rate for ViT backbone

# MPLT
cfg.TRAIN.MPLT_DROP_RATE = 0.  # dropout rate for TransformerDecoderLayer
cfg.TRAIN.MPLT_DROP_PATH = []  # drop_path rate for MPLT Attention_st
cfg.TRAIN.SOT_PRETRAIN = False  # SOT pretraining with shared backbones

# TRAIN.SCHEDULER
cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.TYPE = "step"
cfg.TRAIN.SCHEDULER.DECAY_RATE = 0.1

# DATA
cfg.DATA = edict()
cfg.DATA.SAMPLER_MODE = "causal"  # sampling methods
cfg.DATA.MEAN = [0.485, 0.456, 0.406]
cfg.DATA.STD = [0.229, 0.224, 0.225]
cfg.DATA.DEPTH_PREPROCESS = "rgbcolormap"
cfg.DATA.MAX_SAMPLE_INTERVAL = 200
# DATA.TRAIN
cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.DATASETS_NAME = ["LASOT", "GOT10K_vottrain"]
cfg.DATA.TRAIN.DATASETS_RATIO = [1, 1]
cfg.DATA.TRAIN.SAMPLE_PER_EPOCH = 60000
cfg.DATA.TRAIN.HARD_CLASSES = []
cfg.DATA.TRAIN.HARD_CLASS_PROB = 0.0
# DATA.VAL
cfg.DATA.VAL = edict()
cfg.DATA.VAL.DATASETS_NAME = ["GOT10K_votval"]
cfg.DATA.VAL.DATASETS_RATIO = [1]
cfg.DATA.VAL.SAMPLE_PER_EPOCH = 10000
# DATA.SEARCH
cfg.DATA.SEARCH = edict()
cfg.DATA.SEARCH.SIZE = 320
cfg.DATA.SEARCH.FACTOR = 5.0
cfg.DATA.SEARCH.CENTER_JITTER = 4.5
cfg.DATA.SEARCH.SCALE_JITTER = 0.5
cfg.DATA.SEARCH.NUMBER = 1
# DATA.TEMPLATE
cfg.DATA.TEMPLATE = edict()
cfg.DATA.TEMPLATE.NUMBER = 1
cfg.DATA.TEMPLATE.SIZE = 128
cfg.DATA.TEMPLATE.FACTOR = 2.0
cfg.DATA.TEMPLATE.CENTER_JITTER = 0
cfg.DATA.TEMPLATE.SCALE_JITTER = 0

# TEST
cfg.TEST = edict()
cfg.TEST.TEMPLATE_FACTOR = 2.0
cfg.TEST.TEMPLATE_SIZE = 128
cfg.TEST.SEARCH_FACTOR = 5.0
cfg.TEST.SEARCH_SIZE = 320
cfg.TEST.EPOCH = 500
cfg.TEST.AUTO_DEPTHTRACK_EVAL = False
cfg.TEST.EVAL_EPOCHS = []
cfg.TEST.EVAL_DATASET = "depthtrack_test"
cfg.TEST.EVAL_THREADS = 0
cfg.TEST.EVAL_NUM_GPUS = 1
cfg.TEST.LOW_CONF_DAMPING = True
cfg.TEST.WINDOW_PENALTY_MODE = "multiply"
cfg.TEST.WINDOW_PENALTY = 0.0
cfg.TEST.DAMPING_SCORE_THR = 0.40
cfg.TEST.DAMPING_MIN_UPDATE = 0.25
cfg.TEST.DAMPING_JUMP_FACTOR = 2.0
cfg.TEST.LOST_SCORE_THR = 0.25
cfg.TEST.LOST_UPDATE_RATIO = 0.0
cfg.TEST.LOW_CONF_CENTER_FOLLOW = False
cfg.TEST.CENTER_FOLLOW_SCORE_THR = 0.08
cfg.TEST.CENTER_FOLLOW_UPDATE_RATIO = 0.18
cfg.TEST.CENTER_FOLLOW_MAX_PEAK_DISTANCE = 0.45
cfg.TEST.CENTER_FOLLOW_MAX_RESPONSE_ENTROPY = 0.88
cfg.TEST.CENTER_FOLLOW_MIN_LOST_FRAMES = 0
cfg.TEST.CENTER_FOLLOW_MIN_RESPONSE_ENTROPY = 0.0
cfg.TEST.CENTER_FOLLOW_MAX_SCORE_EMA = 0.0
cfg.TEST.CENTER_FOLLOW_EMA_ALLOW_CONSISTENCY_BELOW = 0.0
cfg.TEST.CENTER_FOLLOW_EMA_ALLOW_RGB_BELOW = 0.0
cfg.TEST.CENTER_FOLLOW_EMA_ALLOW_DEPTH_BELOW = 0.0
cfg.TEST.LOST_MAX_FREEZE_FRAMES = 0
cfg.TEST.LOST_RECOVERY_UPDATE_RATIO = 0.0
cfg.TEST.LOST_RECOVERY_MIN_CONSISTENCY = 0.0
cfg.TEST.RECOVERY_SCORE_THR = 0.35
cfg.TEST.ADAPTIVE_SCORE_DAMPING = False
cfg.TEST.SCORE_EMA_MOMENTUM = 0.95
cfg.TEST.LOST_SCORE_EMA_FACTOR = 0.45
cfg.TEST.DAMPING_SCORE_EMA_FACTOR = 0.85
cfg.TEST.MIN_LOST_SCORE_THR = 0.06
cfg.TEST.MIN_DAMPING_SCORE_THR = 0.15
cfg.TEST.TEMPORAL_PRIOR = True
cfg.TEST.MAX_CENTER_JUMP_FACTOR = 1.25
cfg.TEST.MAX_SCALE_CHANGE = 1.80
cfg.TEST.VELOCITY_MOMENTUM = 0.80
cfg.TEST.VELOCITY_DAMPING = 0.50
cfg.TEST.TEMPLATE_CONSISTENCY_GUARD = False
cfg.TEST.CONSISTENCY_WARMUP_FRAMES = 5
cfg.TEST.CONSISTENCY_SCORE_THR = 0.45
cfg.TEST.CONSISTENCY_UPDATE_RATIO = 0.35
cfg.TEST.CONSISTENCY_HARD_SCORE_THR = 0.25
cfg.TEST.CONSISTENCY_HARD_UPDATE_RATIO = 0.15
cfg.TEST.DEPTH_CONSISTENCY_GUARD = False
cfg.TEST.DEPTH_GUARD_WARMUP_FRAMES = 5
cfg.TEST.DEPTH_CONSISTENCY_THR = 0.35
cfg.TEST.DEPTH_GUARD_SCORE_THR = 0.55
cfg.TEST.DEPTH_GUARD_UPDATE_RATIO = 0.40
cfg.TEST.DEPTH_GUARD_MIN_RGB_CONSISTENCY = 0.0
cfg.TEST.RESPONSE_STABILITY_GUARD = True
cfg.TEST.RESPONSE_GUARD_WARMUP_FRAMES = 5
cfg.TEST.RESPONSE_ENTROPY_THR = 0.72
cfg.TEST.RESPONSE_PEAK_RATIO_THR = 0.92
cfg.TEST.RESPONSE_CENTER_DISTANCE_THR = 0.60
cfg.TEST.RESPONSE_GUARD_UPDATE_RATIO = 0.45
cfg.TEST.CONFIDENT_CONSISTENCY_GUARD = False
cfg.TEST.CONFIDENT_GUARD_SCORE_THR = 0.75
cfg.TEST.CONFIDENT_GUARD_CONSISTENCY_THR = 0.55
cfg.TEST.CONFIDENT_GUARD_DEPTH_THR = 0.0
cfg.TEST.CONFIDENT_GUARD_RGB_THR = 0.0
cfg.TEST.CONFIDENT_GUARD_UPDATE_RATIO = 0.35
cfg.TEST.CONFIDENT_GUARD_HARD_CONSISTENCY_THR = 0.35
cfg.TEST.CONFIDENT_GUARD_HARD_UPDATE_RATIO = 0.20
cfg.TEST.SPATIAL_CONSISTENCY = False
cfg.TEST.SPATIAL_CONSISTENCY_SIZE = 32
cfg.TEST.SPATIAL_CONSISTENCY_RGB_WEIGHT = 0.0
cfg.TEST.SPATIAL_CONSISTENCY_DEPTH_WEIGHT = 0.0
cfg.TEST.DYNAMIC_TEMPLATE = False
cfg.TEST.TEMPLATE_UPDATE_INTERVAL = 100
cfg.TEST.TEMPLATE_UPDATE_SCORE_THR = 0.82
cfg.TEST.TEMPLATE_UPDATE_MIN_STABLE = 8
cfg.TEST.TEMPLATE_UPDATE_MAX_JUMP_FACTOR = 0.75
cfg.TEST.TEMPLATE_UPDATE_BLOCK_ON_GUARD = True
cfg.TEST.TEMPLATE_UPDATE_MIN_CONSISTENCY = 0.0
cfg.TEST.TEMPLATE_UPDATE_MIN_RGB_CONSISTENCY = 0.0
cfg.TEST.TEMPLATE_UPDATE_MIN_DEPTH_CONSISTENCY = 0.0
cfg.TEST.ADAPTIVE_SEARCH_FACTOR = False
cfg.TEST.ADAPTIVE_SEARCH_START_LOST = 1
cfg.TEST.ADAPTIVE_SEARCH_SCORE_THR = 0.0
cfg.TEST.ADAPTIVE_SEARCH_STEP = 0.5
cfg.TEST.ADAPTIVE_SEARCH_MAX_FACTOR = 6.0
cfg.TEST.ADAPTIVE_SEARCH_REQUIRE_RESPONSE_GUARD = False
cfg.TEST.ADAPTIVE_SEARCH_MAX_CONSISTENCY = 0.0
cfg.TEST.ADAPTIVE_SEARCH_RELIABILITY_GATE = False
cfg.TEST.ADAPTIVE_SEARCH_MIN_DEPTH_CONSISTENCY = 0.0
cfg.TEST.ADAPTIVE_SEARCH_MAX_RGB_CONSISTENCY = 0.0
cfg.TEST.ADAPTIVE_SEARCH_MAX_TEMPLATE_CONSISTENCY = 0.0
cfg.TEST.CONFIDENT_MISMATCH_SEARCH = False
cfg.TEST.CONFIDENT_MISMATCH_SEARCH_FACTOR = 5.5
cfg.TEST.CONFIDENT_MISMATCH_WARMUP_FRAMES = 5
cfg.TEST.CONFIDENT_MISMATCH_SCORE_THR = 0.70
cfg.TEST.CONFIDENT_MISMATCH_MAX_CONSISTENCY = 0.45
cfg.TEST.CONFIDENT_MISMATCH_MAX_RGB_CONSISTENCY = 0.0
cfg.TEST.CONFIDENT_MISMATCH_MAX_DEPTH_CONSISTENCY = 0.0
cfg.TEST.CONFIDENT_MISMATCH_MIN_CENTER_DISTANCE = 0.28
cfg.TEST.CONFIDENT_MISMATCH_MIN_ENTROPY = 0.45
cfg.TEST.CONFIDENT_MISMATCH_MIN_PEAK_RATIO = 0.45
cfg.TEST.CONFIDENT_MISMATCH_PROTECT_CONSISTENCY = 0.78
cfg.TEST.CONFIDENT_MISMATCH_PROTECT_RGB = 0.78
cfg.TEST.CONFIDENT_MISMATCH_PROTECT_ENTROPY = 0.35
cfg.TEST.CONFIDENT_MISMATCH_PROTECT_PEAK_RATIO = 0.35
cfg.TEST.DEPTH_DOMINANT_SEARCH = False
cfg.TEST.DEPTH_DOMINANT_SEARCH_FACTOR = 5.0
cfg.TEST.DEPTH_DOMINANT_MIN_DEPTH = 0.85
cfg.TEST.DEPTH_DOMINANT_MAX_RGB = 0.85
cfg.TEST.DEPTH_DOMINANT_MIN_GAP = 0.12
cfg.TEST.DEPTH_DOMINANT_MIN_ENTROPY = 0.25
cfg.TEST.DEPTH_DOMINANT_MAX_PEAK_RATIO = 0.65
cfg.TEST.DEPTH_DOMINANT_MIN_SCORE = 0.0
cfg.TEST.DEPTH_DOMINANT_MAX_SCORE = 1.0
cfg.TEST.DEPTH_DOMINANT_WARMUP_FRAMES = 5
cfg.TEST.CANDIDATE_RERANK = False
cfg.TEST.CANDIDATE_DIAG_TOPK = 10
cfg.TEST.CANDIDATE_RERANK_TOPK = 5
cfg.TEST.CANDIDATE_RERANK_MIN_SCORE_RATIO = 0.92
cfg.TEST.CANDIDATE_RERANK_TRIGGER_ENTROPY = 0.68
cfg.TEST.CANDIDATE_RERANK_TRIGGER_PEAK_RATIO = 0.82
cfg.TEST.CANDIDATE_RERANK_TRIGGER_MIN_CONSISTENCY = 0.0
cfg.TEST.CANDIDATE_RERANK_WARMUP_FRAMES = 3
cfg.TEST.CANDIDATE_RERANK_MAX_FRAME = 0
cfg.TEST.CANDIDATE_RERANK_MAX_SCORE = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_RGB_CONSISTENCY = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_DEPTH_CONSISTENCY = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_CONSISTENCY = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_RGB_CONSISTENCY_EMA = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_DEPTH_CONSISTENCY_EMA = 0.0
cfg.TEST.CANDIDATE_RERANK_REQUIRE_MIN_CONSISTENCY_EMA = 0.0
cfg.TEST.CANDIDATE_RERANK_CONSISTENCY_EMA_MOMENTUM = 0.95
cfg.TEST.CANDIDATE_RERANK_SCORE_WEIGHT = 0.55
cfg.TEST.CANDIDATE_RERANK_RGB_WEIGHT = 0.25
cfg.TEST.CANDIDATE_RERANK_DEPTH_WEIGHT = 0.15
cfg.TEST.CANDIDATE_RERANK_MOTION_WEIGHT = 0.05
cfg.TEST.CANDIDATE_RERANK_MOTION_SIGMA = 1.50
cfg.TEST.CANDIDATE_RERANK_MIN_GAIN = 0.03
cfg.TEST.CANDIDATE_RERANK_MIN_CONSISTENCY_GAIN = 0.08
cfg.TEST.CANDIDATE_RERANK_MAX_SELECTED_RANK = 0
cfg.TEST.CANDIDATE_RERANK_SELECTED_MIN_RGB = 0.0
cfg.TEST.CANDIDATE_RERANK_SELECTED_MIN_DEPTH = 0.0
cfg.TEST.CANDIDATE_RERANK_SELECTED_MIN_CONSISTENCY = 0.0
cfg.TEST.CANDIDATE_RERANK_SELECTED_MIN_MOTION = 0.0
cfg.TEST.CANDIDATE_RERANK_UPDATE_RATIO = 1.0
cfg.TEST.CANDIDATE_RERANK_SELECTIVE_RECOVERY = False
cfg.TEST.CANDIDATE_RERANK_RECOVERY_AUGMENT = False
cfg.TEST.CANDIDATE_RERANK_STABLE_SCORE_THR = 0.72
cfg.TEST.CANDIDATE_RERANK_STABLE_EMA_THR = 0.65
cfg.TEST.CANDIDATE_RERANK_STABLE_ENTROPY_MAX = 0.42
cfg.TEST.CANDIDATE_RERANK_STABLE_PEAK_RATIO_MAX = 0.42
cfg.TEST.CANDIDATE_RERANK_STABLE_CONSISTENCY_MIN = 0.58
cfg.TEST.CANDIDATE_RERANK_STABLE_RGB_MIN = 0.58
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MAX_SCORE = 0.62
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MAX_EMA = 0.70
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_ENTROPY = 0.30
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_PEAK_RATIO = 0.25
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_CENTER_DISTANCE = 0.08
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MAX_CONSISTENCY = 0.78
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MAX_DEPTH_CONSISTENCY = 0.55
cfg.TEST.CANDIDATE_RERANK_RECOVERY_TOPK = 12
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_SCORE_RATIO = 0.35
cfg.TEST.CANDIDATE_RERANK_RECOVERY_SCORE_WEIGHT = 0.20
cfg.TEST.CANDIDATE_RERANK_RECOVERY_RGB_WEIGHT = 0.30
cfg.TEST.CANDIDATE_RERANK_RECOVERY_DEPTH_WEIGHT = 0.30
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MOTION_WEIGHT = 0.20
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_GAIN = 0.01
cfg.TEST.CANDIDATE_RERANK_RECOVERY_MIN_CONSISTENCY_GAIN = -0.02
cfg.TEST.CANDIDATE_RERANK_PROBATION_FRAMES = 0
cfg.TEST.LANGUAGE_CANDIDATE_RERANK = False
cfg.TEST.LANGUAGE_CANDIDATE_RESPONSE_TOPK = 12
cfg.TEST.LANGUAGE_CANDIDATE_TOPK = 8
cfg.TEST.LANGUAGE_CANDIDATE_MIN_SCORE_RATIO = 0.02
cfg.TEST.LANGUAGE_CANDIDATE_TRIGGER_GAP = 0.08
cfg.TEST.LANGUAGE_CANDIDATE_MIN_BASE_SCORE = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MIN_BASE_EMA = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MIN_BASE_CONSISTENCY = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MIN_BASE_RGB = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MIN_BASE_DEPTH = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_SCORE = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_EMA = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_CONSISTENCY = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_RGB = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_DEPTH = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_STABLE_BASE_BLOCK = False
cfg.TEST.LANGUAGE_CANDIDATE_STABLE_BASE_CONSISTENCY = 0.82
cfg.TEST.LANGUAGE_CANDIDATE_STABLE_BASE_RGB = 0.82
cfg.TEST.LANGUAGE_CANDIDATE_STABLE_BASE_DEPTH = 0.80
cfg.TEST.LANGUAGE_CANDIDATE_MAX_RESPONSE_ENTROPY = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_RESPONSE_PEAK_RATIO = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MAX_BASE_LANG = 0.0
cfg.TEST.LANGUAGE_CANDIDATE_MIN_LANG_GAIN = 0.04
cfg.TEST.LANGUAGE_CANDIDATE_SCORE_WEIGHT = 0.25
cfg.TEST.LANGUAGE_CANDIDATE_LANG_WEIGHT = 0.45
cfg.TEST.LANGUAGE_CANDIDATE_RGB_WEIGHT = 0.10
cfg.TEST.LANGUAGE_CANDIDATE_DEPTH_WEIGHT = 0.10
cfg.TEST.LANGUAGE_CANDIDATE_MOTION_WEIGHT = 0.10
cfg.TEST.LANGUAGE_CANDIDATE_MIN_GAIN = 0.02
cfg.TEST.LANGUAGE_CANDIDATE_MIN_CONSISTENCY_GAIN = -0.10
cfg.TEST.LANGUAGE_RUNTIME_GATE = False
cfg.TEST.LANGUAGE_GATE_MODE = "legacy"
cfg.TEST.LANGUAGE_GATE_WARMUP_FRAMES = 2
cfg.TEST.LANGUAGE_GATE_MIN = 0.20
cfg.TEST.LANGUAGE_GATE_LOW_SCORE = 0.45
cfg.TEST.LANGUAGE_GATE_VERY_LOW_SCORE = 0.25
cfg.TEST.LANGUAGE_GATE_HIGH_SCORE = 0.75
cfg.TEST.LANGUAGE_GATE_UNSTABLE_ENTROPY = 0.68
cfg.TEST.LANGUAGE_GATE_UNSTABLE_PEAK_RATIO = 0.82
cfg.TEST.LANGUAGE_GATE_UNSTABLE_CENTER_DISTANCE = 0.12
cfg.TEST.LANGUAGE_GATE_STABLE_ENTROPY = 0.45
cfg.TEST.LANGUAGE_GATE_STABLE_PEAK_RATIO = 0.45
cfg.TEST.LANGUAGE_GATE_STABLE_CONSISTENCY = 0.78
cfg.TEST.LANGUAGE_GATE_STABLE_DEPTH_CONSISTENCY = 0.50
cfg.TEST.LANGUAGE_GATE_LOW_CONSISTENCY = 0.45
cfg.TEST.LANGUAGE_GATE_LOW_DEPTH_CONSISTENCY = 0.25
cfg.TEST.LANGUAGE_GATE_GEOM_RGB_MIN = 0.68
cfg.TEST.LANGUAGE_GATE_GEOM_CONSISTENCY_MIN = 0.65
cfg.TEST.LANGUAGE_GATE_GEOM_DEPTH_MAX = 0.30
cfg.TEST.LANGUAGE_GATE_GEOM_ENTROPY_MAX = 0.50
cfg.TEST.LANGUAGE_GATE_GEOM_PEAK_RATIO_MAX = 0.55
cfg.TEST.SCORE_CALIBRATION = False
cfg.TEST.SCORE_CALIBRATION_WARMUP_FRAMES = 5
cfg.TEST.SCORE_CALIBRATION_MIN = 0.25
cfg.TEST.SCORE_CALIBRATION_TEMPLATE_THR = 0.45
cfg.TEST.SCORE_CALIBRATION_RGB_THR = 0.45
cfg.TEST.SCORE_CALIBRATION_DEPTH_THR = 0.20
cfg.TEST.SCORE_CALIBRATION_RESPONSE_ENTROPY_THR = 0.65
cfg.TEST.SCORE_CALIBRATION_PEAK_RATIO_THR = 0.75
cfg.TEST.SCORE_CALIBRATION_CENTER_DISTANCE_THR = 0.35
cfg.TEST.SCORE_CALIBRATION_LOW_UPDATE_THR = 0.40
cfg.TEST.SCORE_CALIBRATION_TEMPLATE_WEIGHT = 0.25
cfg.TEST.SCORE_CALIBRATION_RGB_WEIGHT = 0.15
cfg.TEST.SCORE_CALIBRATION_DEPTH_WEIGHT = 0.10
cfg.TEST.SCORE_CALIBRATION_RESPONSE_WEIGHT = 0.20
cfg.TEST.SCORE_CALIBRATION_UPDATE_WEIGHT = 0.10
cfg.TEST.SCORE_CALIBRATION_PROTECT_SCORE = 0.80
cfg.TEST.SCORE_CALIBRATION_PROTECT_CONSISTENCY = 0.70
cfg.TEST.SCORE_CALIBRATION_PROTECT_RGB = 0.70
cfg.TEST.SCORE_CALIBRATION_PROTECT_ENTROPY = 0.45
cfg.TEST.SCORE_CALIBRATION_PROTECT_PEAK_RATIO = 0.45


def _edict2dict(dest_dict, src_edict):
    if isinstance(dest_dict, dict) and isinstance(src_edict, dict):
        for k, v in src_edict.items():
            if not isinstance(v, edict):
                dest_dict[k] = v
            else:
                dest_dict[k] = {}
                _edict2dict(dest_dict[k], v)
    else:
        return


def gen_config(config_file):
    cfg_dict = {}
    _edict2dict(cfg_dict, cfg)
    with open(config_file, 'w') as f:
        yaml.dump(cfg_dict, f, default_flow_style=False)


def _update_config(base_cfg, exp_cfg):
    if isinstance(base_cfg, dict) and isinstance(exp_cfg, edict):
        for k, v in exp_cfg.items():
            if k in base_cfg:
                if not isinstance(v, dict):
                    base_cfg[k] = v
                else:
                    _update_config(base_cfg[k], v)
            else:
                raise ValueError("{} not exist in config.py".format(k))
    else:
        return


def update_config_from_file(filename, base_cfg=None):
    exp_config = None
    with open(filename) as f:
        exp_config = edict(yaml.safe_load(f))
        if base_cfg is not None:
            _update_config(base_cfg, exp_config)
        else:
            _update_config(cfg, exp_config)
